spring:
  application:
    name: spring-data-rest-example

  datasource:
    driver-class-name: ${MYSQL_DRIVER}
    url: ${MYSQL_URL}
    username: ${MYSQL_USER}
    password: ${MYSQL_PW}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update